// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CreateFrom : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
DECLARE @defaultCurrencyCode as varchar(10) = (Select top 1 ss.[DefaultCurrency_FK] from crm.[SystemSettings] ss where ss.[Deleted] = 0 Order By ss.[Id])
DECLARE @defaultCurrencyId as int = (Select top 1 c.[Id] from [crm].[Currency] c where c.[IsoCode] = @defaultCurrencyCode AND c.[Deleted] = 0)
--DECLARE @IssuerAccount_FK int = [crm].[GetDefaultCompanyID]()

	
SELECT 
	0 as [Version]
	");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
  WriteSelectColumn(); 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 16 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
 WriteGrids(); 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\r\n\t");
            
            #line 18 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"

	if (projectionNameTarget == "Email") {
	
            
            #line default
            #line hidden
            this.Write(@"	,(SELECT
		cast(0 as bit) as [Deleted]
		,vwp1.[DbObject_Id] as [DbObject_Id]
		,vwp1.[DbObject_Schema] as [DBObject_Schema]
		,vwp1.[DbObject_Name] as [DbObject_Name]
		,vwp1.[Projection_Name] as [MainProjection]
		,isnull((SELECT TOP 1 ls.[value] FROM [crm].[LocalizationString] ls WHERE ls.[Language_Fk] = @userLanguageId and ls.[Area_Fk] = (SELECT TOP 1 la1.[Id] FROM [crm].[LocalizationArea] la1 WHERE la1.[Name] = vwp1.[Projection_Name]) and ls.[key] = 'NameTitle' ORDER BY [customized] DESC) , vwp1.[Projection_Name]) as [ProjectionTitle] 
		,vwp1.[Projection_Icon] as [Icon]
		,@id as [RecordId]
		,[");
            
            #line 30 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[Created] as [Created]\r\n\t\t,[");
            
            #line 31 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[CreatedBy_FK] as [CreatedBy_FK]\r\n\t\t,u1.[CaptionDisplay] as [CreatedBy_FK_Capti" +
                    "on]\r\n\t\t,[");
            
            #line 33 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[Modified] as [Modified]\r\n\t\t,[");
            
            #line 34 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[ModifiedBy_FK] as [ModifiedBy_FK]\r\n\t\t,u2.[CaptionDisplay] as [ModifiedBy_FK_Ca" +
                    "ption]\r\n\t\t,[");
            
            #line 36 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[CaptionDisplay] as [CaptionDisplay]\r\n\t  FROM [crm].[vwProjection] vwp1 \r\n\t  LE" +
                    "FT OUTER JOIN [crm].[User] u1 ON u1.[Deleted] = 0 and u1.[Id] = [");
            
            #line 38 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[CreatedBy_FK]\r\n\t  LEFT OUTER JOIN [crm].[User] u2 ON u2.[Deleted] = 0 and u2.[" +
                    "Id] = [");
            
            #line 39 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[ModifiedBy_FK]\r\n\t  WHERE vwp1.[DbObject_Id] = ");
            
            #line 40 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.DbObject_Id));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tand vwp1.[Projection_Name] = \'");
            
            #line 41 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\tand vwp1.[Profile_Id] = ");
            
            #line 42 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(userInfo.ProfileId));
            
            #line default
            #line hidden
            this.Write("\r\n\tFOR JSON PATH, INCLUDE_NULL_VALUES)\r\n\tas [DbObjectsRecords]\r\n\t");
            
            #line 45 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nFROM [");
            
            #line 47 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 47 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] as [");
            
            #line 47 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("]\r\nWHERE [");
            
            #line 48 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 48 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\CreateFrom.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(projectionFrom.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] = @id\r\nFOR JSON PATH, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
