// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetById : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n");
            
            #line 6 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
	
if (vwProjection.DbObject_Name == "Email")
{

            
            #line default
            #line hidden
            this.Write("declare @jsonDbObjectsForEmail nvarchar(max)\r\nexec [dbo].[sp_api3_GetDbObjectsFor" +
                    "Email] @id, ");
            
            #line 11 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(userInfo.ProfileId));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 11 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(userInfo.UserLanguageId));
            
            #line default
            #line hidden
            this.Write(", @jsonDbObjectsForEmail out\r\ndeclare @jsonDirectoriesForEmail nvarchar(max)\r\nexe" +
                    "c [dbo].[sp_api3_GetDirectoriesForEmail] @id, ");
            
            #line 13 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(userInfo.ProfileId));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 13 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(userInfo.UserLanguageId));
            
            #line default
            #line hidden
            this.Write(", @jsonDirectoriesForEmail out\r\n");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
	
}

            
            #line default
            #line hidden
            this.Write("\r\nSELECT top 1\r\n\t[");
            
            #line 19 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 19 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] as [Id]\r\n\t");
            
            #line 20 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
if (vwProjection.DbObjectType_Id == 1)
	{
            
            #line default
            #line hidden
            this.Write("\t,[");
            
            #line 22 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[CaptionDisplay] as \t[Caption]\r\n\t,[");
            
            #line 23 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[CreatedBy_FK]\r\n\t,(select top 1 s.[UserName] from [crm].[User] s where s.Id = [" +
                    "");
            
            #line 24 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[CreatedBy_FK]) as [CreatedBy_FK_Caption]\r\n\t,[");
            
            #line 25 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[Created]\r\n\t,[");
            
            #line 26 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[ModifiedBy_FK]\r\n\t,(select top 1 s.[UserName] from [crm].[User] s where s.Id = " +
                    "[");
            
            #line 27 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[ModifiedBy_FK]) as [ModifiedBy_FK_Caption]\r\n\t,[");
            
            #line 28 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[Modified]\r\n\t");
            
            #line 29 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
 }
	if (vwProjection.Projection_Name == "Email")
	{
            
            #line default
            #line hidden
            this.Write("\t\t,cast(iif([");
            
            #line 32 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[FlagStatus]& 16 > 0, 0, 1) as bit) as [Locked]\r\n\t");
            
            #line 33 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
} 

	PushIndent("	");

	foreach(var col in columns){
		WriteColumnBracketedString(col);
		WriteCaptionStringForColumn(col);
		Write(Environment.NewLine);
	}
	if (vwProjection.DbObject_Name != "User" && vwProjection.DbObjectType_Id == 1 && !simple)
	{
		//WriteCategoriesForEntity();
	}
	WriteGrids();
	
	if (vwProjection.Object_ParticipantEnabled && !simple)
	{
	
            
            #line default
            #line hidden
            this.Write(@"	,(SELECT r1.[Id] as [RoleId]
		,pa1.[User_FK] as [UserId]
		,u1.[CaptionDisplay] as [UserCaption]
	  FROM [crm].[Participant] pa1
	  INNER JOIN [crm].[DbObjectRole] dor1 ON dor1.[Deleted] = 0 AND dor1.[Id] = pa1.[DbObjectRole_FK] AND dor1.[DbObject_FK] = ");
            
            #line 55 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write(@"
	  INNER JOIN [crm].[Role] r1 ON r1.[Deleted] = 0 AND r1.[Id] = dor1.[Role_FK]
	  INNER JOIN [crm].[User] u1 ON u1.[Deleted] = 0 AND u1.[Id] = pa1.[User_FK]
	  WHERE pa1.[Deleted] = 0
	  AND pa1.[RecordId] = @id
	  FOR JSON PATH, INCLUDE_NULL_VALUES)
	as [Participants]
	");
            
            #line 62 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"

	}
	
	if (vwProjection.Object_DocumentEnabled && !simple)
	{
	
            
            #line default
            #line hidden
            this.Write("\t,(SELECT\r\n\t\t[Document].[Id] as [Id]\r\n\t\t,[Document].[Deleted]\r\n\t\t,[Document].[Cap" +
                    "tionSort]\r\n\t\t,[Document].[CaptionDisplay]\r\n\t\t,[Document].[Name] as [Subject]\r\n\t\t" +
                    ",[DocumentType].[Description_");
            
            #line 74 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(userInfo.UserLanguage));
            
            #line default
            #line hidden
            this.Write(@"] as [Type_FK]
		,isnull((SELECT count(*) FROM [crm].[DocumentAttachment] as [da1] WHERE [da1].[Deleted] = 0 AND [da1].[Document_FK] = [Document].[Id]),0) as [AttachmentCount]
		,case isnull((SELECT count(*) FROM [crm].[DocumentAttachment] as [da1] WHERE [da1].[Deleted] = 0 AND [da1].[Document_FK] = [Document].[Id]),0)
			when 1 then isnull((SELECT TOP 1 isnull([da1].[Icon], [dbo].[fn_GetIconByFileName]([da1].[DocName])) FROM [crm].[DocumentAttachment] as [da1] WHERE [da1].[Deleted] = 0 AND [da1].[Document_FK] = [Document].[Id]),'fa-file-o')
			else 'fa-file-archive-o'
			end as [Icon]
		,row_number() OVER (ORDER BY [Document].[CaptionSort] ASC) AS [QueueOrder]
	FROM [crm].[Document] as [Document]
	LEFT OUTER JOIN [crm].[Enumeration] [DocumentType] on [DocumentType].[Id] = [Document].[Type_FK]
	WHERE [Document].[Deleted] = 0
		--and [Document].[Id] not in (SELECT Entity_FK FROM [crm].[fn_GetBannedEntityIds] (@userId, 8, 1))
		and [Document].[Id] in ( SELECT dod1.[Document_FK] FROM [crm].[DbObjectDocument] dod1 WHERE dod1.[Deleted] = 0 and dod1.[DbObject_FK] = ");
            
            #line 85 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write(" and dod1.[RecordId] = @id) \r\n\tORDER BY [QueueOrder]\r\n\tFOR JSON PATH, INCLUDE_NUL" +
                    "L_VALUES)\r\n\tas [Document]\r\n\r\n\t");
            
            #line 90 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"

	}

	if (!simple)
	{
	
            
            #line default
            #line hidden
            this.Write("\t\t,(\r\n\t\t\tSELECT  count (*)\r\n\t\t\tFROM [crm].[Email] AS [Project1]\r\n\t\t\t\twhere [Proje" +
                    "ct1].[Deleted] = 0\r\n\t\t\t\tand (([Project1].[Id] in (SELECT doe1.[Email_FK] FROM [c" +
                    "rm].[DbObjectEmail] doe1 WHERE doe1.[Deleted] = 0 and doe1.[DbObject_FK] = ");
            
            #line 100 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write(@" and doe1.[RecordId] = @id)))
		) as [RecordEmailsCount]
		,(
			SELECT  count (*)
			FROM [crm].[Email] AS [Project1]
				where [Project1].[Deleted] = 0
				and (([Project1].[Id] in (SELECT doe1.[Email_FK] FROM [crm].[DbObjectEmail] doe1 WHERE doe1.[Deleted] = 0 and doe1.[DbObject_FK] = ");
            
            #line 106 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write(" and doe1.[RecordId] = @id)))\r\n\t\t\t\tand [Project1].[IsLinkedWithVistos] = 1\r\n\t   )" +
                    " as [RecordEmailsIsLinkedWithVistosCount]\r\n\t");
            
            #line 109 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"

	}

	if (vwProjection.DbObject_Name == "Email")
	{
	
            
            #line default
            #line hidden
            this.Write(@"	,(SELECT [Id]
	  ,[Deleted]
      ,[CreatedBy_FK]
      ,[Created]
      ,[ModifiedBy_FK]
      ,[Modified]
      ,[FileName]
      ,[CID]
      ,[Type]
      ,[DataLength]
	  FROM [crm].[EmailAttachment] ea1
	  WHERE ea1.[Deleted] = 0 AND ea1.[Email_FK] = @id
		ORDER BY [FileName]
		FOR JSON PATH, INCLUDE_NULL_VALUES)
	as [EmailAttachment]
	,JSON_QUERY(@jsonDbObjectsForEmail) as [DbObjectsRecords]
	,JSON_QUERY(@jsonDirectoriesForEmail) as [DirectoriesRecords]
	");
            
            #line 132 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"

	}

	PopIndent();

            
            #line default
            #line hidden
            this.Write("FROM [");
            
            #line 137 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 137 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] as [");
            
            #line 137 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n");
            
            #line 138 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"

WriteWhereFilter();

            
            #line default
            #line hidden
            this.Write("and [");
            
            #line 141 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 141 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetById.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] = @id\r\nFOR JSON PATH, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER\r\n\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
