// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Core.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetByIdItemGrid : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n, ( \r\nSELECT \r\n\t[");
            
            #line 10 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[CaptionDisplay] as \t[Caption]\r\n\t,[");
            
            #line 11 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[CreatedBy_FK]\r\n\t,(select top 1 s.[UserName] from [crm].[User] s where s.Id = [" +
                    "");
            
            #line 12 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[CreatedBy_FK]) as [CreatedBy_FK_Caption]\r\n\t,[");
            
            #line 13 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[Created]\r\n\t,[");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[ModifiedBy_FK]\r\n\t,(select top 1 s.[UserName] from [crm].[User] s where s.Id = " +
                    "[");
            
            #line 15 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[ModifiedBy_FK]) as [ModifiedBy_FK_Caption]\r\n\t,[");
            
            #line 16 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[Modified]\r\n\t,[");
            
            #line 17 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[Deleted]\r\n\t");
            
            #line 18 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"


	PushIndent("	");
	foreach(var col in columns){
		WriteColumnBracketedString(col);
		WriteCaptionStringForColumn(col);
		Write(Environment.NewLine);
	}
	PopIndent();

	if (relation.ProjectionRelation_Type_FK == (int)DbRelationTypeEnum.ItemMasterGrid) { 
            
            #line default
            #line hidden
            this.Write("\t,(\r\n\t\tSELECT top 1 [");
            
            #line 30 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("2].[");
            
            #line 30 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\tfrom [");
            
            #line 31 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.DbObject1_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 31 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.DbObject1_Name));
            
            #line default
            #line hidden
            this.Write("] [");
            
            #line 31 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("2]\r\n\t\twhere [");
            
            #line 32 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("2].[");
            
            #line 32 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] < [");
            
            #line 32 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 32 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] and [");
            
            #line 32 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("2].[Type] = \'BlockLabel\' and [");
            
            #line 32 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[Type] = \'Item\'\r\n\t\torder by [");
            
            #line 33 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("2].[");
            
            #line 33 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] desc\r\n\t) as [Parent_FK]\t\r\n\t");
            
            #line 35 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
 }


            
            #line default
            #line hidden
            this.Write("FROM [");
            
            #line 38 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.DbObject1_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 38 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.DbObject1_Name));
            
            #line default
            #line hidden
            this.Write("] [");
            
            #line 38 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("]\r\nwhere [");
            
            #line 39 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[Deleted] = 0\r\nand [");
            
            #line 40 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 40 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.DbColumn1_Name));
            
            #line default
            #line hidden
            this.Write("] = [");
            
            #line 40 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentEntity.Projection_Name));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 40 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentEntity.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n");
            
            #line 41 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"

WriteWhereFilter();

            
            #line default
            #line hidden
            this.Write("ORDER BY [");
            
            #line 44 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 44 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.DbColumn_NameSortBy));
            
            #line default
            #line hidden
            this.Write("]\r\nFOR JSON PATH, INCLUDE_NULL_VALUES)\r\nas [");
            
            #line 46 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetByIdItemGrid.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation.ProjectionRelation_ChildProjectionName));
            
            #line default
            #line hidden
            this.Write("]\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
