// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using QueryBuilder.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetCalendarEntities : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 8 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
 
   bool isFirst = true;

   foreach (var p in CalendarProjections)
   {
		var roles = EntitiesAndRoles[p.Projection_Name];

		if (roles.Count > 0) 
		{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 17 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isFirst ? string.Empty : "UNION"));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t\t\t");
            
            #line 19 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
 isFirst = false; 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tSELECT E.[Id],\r\n\t\t\t\'");
            
            #line 22 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Projection_Name));
            
            #line default
            #line hidden
            this.Write("\' AS EntityName, \r\n\t\t\tISNULL(E.[CaptionDisplay], CONVERT(nvarchar(MAX), E.Id)) AS" +
                    " [Name], \r\n\t\t\tE.[");
            
            #line 24 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EventStartColumnName));
            
            #line default
            #line hidden
            this.Write("] AS StartDate, \r\n\t\t\tE.[");
            
            #line 25 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EventEndColumnName));
            
            #line default
            #line hidden
            this.Write("] AS EndDate,\r\n\t\t\tCASE WHEN E.[");
            
            #line 26 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EventStartColumnName));
            
            #line default
            #line hidden
            this.Write("] = CAST(E.[");
            
            #line 26 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EventStartColumnName));
            
            #line default
            #line hidden
            this.Write("] AS date) AND E.[");
            
            #line 26 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EventEndColumnName));
            
            #line default
            #line hidden
            this.Write("] = CAST(E.[");
            
            #line 26 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EventEndColumnName));
            
            #line default
            #line hidden
            this.Write("] AS date) THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END AS IsAllDay,\r\n\t\t\t\'");
            
            #line 27 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.CalendarBackgroundColor ?? string.Empty));
            
            #line default
            #line hidden
            this.Write("\' AS CalendarBackgroundColor\r\n\t\r\n\t\t\tFROM [");
            
            #line 29 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 29 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] E\r\n\t\r\n\t\t\tWHERE E.[Deleted] = 0 AND E.[");
            
            #line 31 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EventStartColumnName));
            
            #line default
            #line hidden
            this.Write("] < @toDate AND E.[");
            
            #line 31 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EventEndColumnName));
            
            #line default
            #line hidden
            this.Write("] > @fromDate\r\n\t\t\tAND E.[Id] in (\r\n\t\t\t\tSELECT p1.[RecordId]\r\n\t\t\t\tFROM [crm].[Part" +
                    "icipant] p1\r\n\t\t\t\tINNER JOIN [crm].[DbObjectRole] dor1 ON dor1.[Deleted] = 0 AND " +
                    "dor1.[Id] = p1.[DbObjectRole_FK] AND dor1.[Role_FK] IN (");
            
            #line 35 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetListValues(roles)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\tWHERE p1.[Deleted] = 0\r\n\t\t\t\t\tAND p1.[User_FK] IN (");
            
            #line 37 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetListValues(UserIDs)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t)\r\n");
            
            #line 39 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetCalendarEntities.tt"
 		}
	} 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
