// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using QueryBuilder.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetExport : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n\tSET NOCOUNT ON; \r\n\r\n\t\tSELECT\r\n\t\t\t[Entity1].[Id]\r\n\t\t\t");
            
            #line 12 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"

			PushIndent("			");
            foreach(string columnName in this.columnsVisible)
            {
                var col = this.columns.Where(c => c.ProjectionColumn_Name == columnName).FirstOrDefault();
                if (col != null)
                {
                    WriteColumnForEntity1Select(col);
                    Write(Environment.NewLine);
                }
            }
			PopIndent();
			foreach(var col in columnsVisible.Where(c => c.StartsWith("Role__"))){
            
            #line default
            #line hidden
            this.Write("\t\t\t,[Entity1].[");
            
            #line 25 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col));
            
            #line default
            #line hidden
            this.Write("] as [");
            
            #line 25 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t\t");
            
            #line 26 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"

			}
			if (vwProjection.Object_CategoriesEnabled)
			{
            
            #line default
            #line hidden
            this.Write("\t\t\t,[Entity1].[EntityCategories]\r\n\t\t\t");
            
            #line 31 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\tFROM (\r\n\t\t\tSELECT\r\n\t\t\t\t[Project1].[");
            
            #line 34 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] as [Id]\r\n\t\t\t\t,[Project1].[CaptionSort]\r\n\t\t\t\t");
            
            #line 36 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
				PushIndent("				");
				foreach(string columnName in this.columnsVisible)
				{
					var col = this.columns.Where(c => c.ProjectionColumn_Name == columnName).FirstOrDefault();
					if (col != null)
					{
						WriteColumnForProject1Select(col);
						Write(Environment.NewLine);
					}
				}
				if (!this.columnsVisible.Any(x => x == sortOrderColumnName))
				{
					var col = this.columns.Where(c => c.ProjectionColumn_Name == sortOrderColumnName).FirstOrDefault();
					if (col != null)
					{
						WriteColumnForProject1Select(col);
						Write(Environment.NewLine);
					}
				}
				PopIndent();
				foreach(var col in columnsVisible.Where(c => c.StartsWith("Role__"))){
            
            #line default
            #line hidden
            this.Write(@"				,(	STUFF((
						SELECT ',' + usr1.[CaptionDisplay]
						FROM [crm].[Participant] part1
						INNER JOIN [crm].[User] usr1 ON usr1.[Deleted] = 0 AND usr1.[Id] = part1.[User_FK]
						INNER JOIN [crm].[DbObjectRole] dor1 ON dor1.[Deleted] = 0 AND dor1.[Id] = part1.[DbObjectRole_FK] AND dor1.[DbObject_FK] = ");
            
            #line 61 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\tINNER JOIN [crm].[Role] role1 ON role1.[Deleted] = 0 AND role1.[Id] = dor" +
                    "1.[Role_FK] AND role1.[Name] = \'");
            
            #line 62 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Replace("Role__","")));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\t\t\t\t\tWHERE part1.[Deleted] = 0\r\n\t\t\t\t\t\t\tAND part1.[RecordId] = [Project1].[");
            
            #line 64 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t\t\t\t\tFOR XML PATH(\'\')\r\n\t\t\t\t\t),1,1,\'\')\r\n\t\t\t\t) as [");
            
            #line 67 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 67 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"

				}
				
            
            #line default
            #line hidden
            this.Write("\t\t\tFROM  [");
            
            #line 70 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 70 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] AS [Project1]\r\n\t\t\t");
            
            #line 71 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
 
				PushIndent("			");
				WriteLeftOuterJoin(WriteLeftOuterJoinType.ForData);
				PopIndent();
			
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 76 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"

				PushIndent("				");
				WriteWhereFilter();
				WriteFilter();
				PopIndent();
				
            
            #line default
            #line hidden
            this.Write("\t\t\t) AS [Entity1]\r\n\r\n\t\tORDER BY ");
            
            #line 84 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetExport.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortOrder_Entity));
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
