// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using QueryBuilder.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridIds.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetGridIds : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n\tSET NOCOUNT ON; \r\n\t\t\r\n\t\t\tSELECT\r\n\t\t\t\t[Project1].[");
            
            #line 11 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridIds.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] as [Id]\r\n\t\t\tFROM  [");
            
            #line 12 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridIds.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 12 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridIds.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] AS [Project1]\r\n\t\t\t");
            
            #line 13 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridIds.tt"
 
				PushIndent("			");
				WriteLeftOuterJoin(WriteLeftOuterJoinType.ForData);
				PopIndent();
			
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 18 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridIds.tt"

				PushIndent("				");
				WriteWhereFilter();
				WriteFilter();
				PopIndent();
				
            
            #line default
            #line hidden
            this.Write("\tFOR JSON PATH, INCLUDE_NULL_VALUES\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
