// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using QueryBuilder.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetGridCount : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nSET NOCOUNT ON; \r\n\r\n");
            
            #line 10 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"

if (vwProjection.DbObject_Name == "EntityActivity")
{

            
            #line default
            #line hidden
            this.Write("    declare @parentRecordId int = ");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentEntityId));
            
            #line default
            #line hidden
            this.Write("\r\n    declare @parentDbObjectId int = ");
            
            #line 15 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentDbObject_Id));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n    CREATE TABLE #Data1([Count] [int])\r\n\r\n    declare @dbObjectId int\r\n    de" +
                    "clare @DbObjectName [varchar](250)\r\n    declare @DbObjectSchema [varchar](50)\r\n " +
                    "   declare @dbObjectTypeId int\r\n    declare cData1 cursor local for\r\n           " +
                    " SELECT distinct\r\n                [Id]\r\n                ,[DbObjectType_FK]\r\n    " +
                    "            ,[Name]\r\n                ,[Schema]\r\n            FROM (\r\n            " +
                    "    SELECT distinct\r\n                    vwp1.[DbObject_Id] as [Id]\r\n           " +
                    "         ,vwp1.[DbObjectType_Id] as [DbObjectType_FK]\r\n                    ,vwp1" +
                    ".[DbObject_Name] as [Name]\r\n                    ,vwp1.[DbObject_Schema] as [Sche" +
                    "ma]\r\n                FROM [crm].[DbColumn] c1\r\n                INNER JOIN [crm]." +
                    "[vwProjection] vwp1 on vwp1.[DbObject_Id] = c1.[DbObject_FK] and vwp1.[Projectio" +
                    "n_ActivityEnabled] = 1 and vwp1.[Profile_Id] = @profileId and vwp1.[AccessRight]" +
                    " > 0\r\n                WHERE c1.[Deleted] = 0\r\n                    and c1.[Refere" +
                    "nceDbObject_FK] = @parentDbObjectId\r\n                    and vwp1.[DbObjectType_" +
                    "Id] in (1, 5)\r\n                UNION\r\n                SELECT distinct\r\n         " +
                    "           vwp1.[DbObject_Id] as [Id]\r\n                    ,vwp1.[DbObjectType_I" +
                    "d] as [DbObjectType_FK]\r\n                    ,vwp1.[DbObject_Name] as [Name]\r\n  " +
                    "                  ,vwp1.[DbObject_Schema] as [Schema]\r\n                FROM [crm" +
                    "].[DbObjectDbObject] oo1\r\n                INNER JOIN [crm].[vwProjection] vwp1 o" +
                    "n vwp1.[DbObject_Id] = oo1.[RightDbObject_FK] and vwp1.[Projection_ActivityEnabl" +
                    "ed] = 1 and vwp1.[Profile_Id] = @profileId and vwp1.[AccessRight] > 0\r\n         " +
                    "       where oo1.[Deleted] = 0 and oo1.[LeftDbObject_FK] = @parentDbObjectId and" +
                    " oo1.[LeftRecordId] = @parentDbObjectId\r\n                UNION\r\n                " +
                    "SELECT distinct\r\n                    vwp1.[DbObject_Id] as [Id]\r\n               " +
                    "     ,vwp1.[DbObjectType_Id] as [DbObjectType_FK]\r\n                    ,vwp1.[Db" +
                    "Object_Name] as [Name]\r\n                    ,vwp1.[DbObject_Schema] as [Schema]\r" +
                    "\n                FROM [crm].[DbObjectDbObject] oo1\r\n                INNER JOIN [" +
                    "crm].[vwProjection] vwp1 on vwp1.[DbObject_Id] = oo1.[LeftDbObject_FK] and vwp1." +
                    "[Projection_ActivityEnabled] = 1 and vwp1.[Profile_Id] = @profileId and vwp1.[Ac" +
                    "cessRight] > 0\r\n                where oo1.[Deleted] = 0 and oo1.[RightDbObject_F" +
                    "K] = @parentDbObjectId and oo1.[RightRecordId] = @parentDbObjectId\r\n            " +
                    ") obj1\r\n\r\n    open cData1\r\n    fetch next from cData1 into @dbObjectId, @dbObjec" +
                    "tTypeId, @DbObjectName, @DbObjectSchema\r\n    while @@FETCH_STATUS=0\r\n    begin\r\n" +
                    "        declare @whereCols0 varchar(max) = \'\'\r\n        declare @whereCols1 varch" +
                    "ar(max) = \'\'\r\n        declare @whereCols2 varchar(max) = \'\'\r\n        declare @wh" +
                    "ereCols3 varchar(max) = \'\'\r\n        declare @select1 varchar(max) = \'\'\r\n\r\n      " +
                    "  set @select1 = \'SELECT distinct Entity1.[Id]\'\r\n        set @select1 = @select1" +
                    " + \' FROM [\' + @DbObjectSchema + \'].[\' + @DbObjectName + \'] as Entity1 \'\r\n\r\n    " +
                    "    IF (@dbObjectTypeId = 1)\r\n        BEGIN\r\n            set @select1 = @select1" +
                    " + \' WHERE Entity1.[Deleted] = 0 \'\r\n        END\r\n        ELSE\r\n        BEGIN\r\n  " +
                    "          set @select1 = @select1 + \' WHERE 1 = 1 \'\r\n        END\r\n\r\n        SELE" +
                    "CT @whereCols1 = coalesce(@whereCols1 + \'\', \'\') + \'or Entity1.[\' + convert(varch" +
                    "ar,c1.[Name]) + \'] = \' + CAST(@parentRecordId as varchar) + \' \'\r\n        FROM [c" +
                    "rm].[DbColumn] c1\r\n        WHERE c1.[Deleted] = 0\r\n            and c1.DbObject_F" +
                    "K = @dbObjectId\r\n            and c1.[ReferenceDbObject_FK] = @parentDbObjectId\r\n" +
                    "            and c1.[ComputedExpression] is null\r\n        order by c1.QueueOrder\r" +
                    "\n\r\n        set @whereCols2 = \' or Entity1.[Id] in (SELECT oo1.[LeftRecordId] FRO" +
                    "M [crm].[DbObjectDbObject] oo1 WHERE oo1.[Deleted] = 0 and oo1.[RightDbObject_FK" +
                    "] = \' + cast(@parentDbObjectId as varchar) + \' and oo1.[RightRecordId] = \' + cas" +
                    "t(@parentRecordId as varchar) + \' and oo1.[LeftDbObject_FK] = \' + cast(@dbObject" +
                    "Id as varchar) + \')\'\r\n        set @whereCols3 = \' or Entity1.[Id] in (SELECT oo1" +
                    ".[RightRecordId] FROM [crm].[DbObjectDbObject] oo1 WHERE oo1.[Deleted] = 0 and o" +
                    "o1.[LeftDbObject_FK] = \' + cast(@parentDbObjectId as varchar) + \' and oo1.[LeftR" +
                    "ecordId] = \' + cast(@parentRecordId as varchar) + \' and oo1.[RightDbObject_FK] =" +
                    " \' + cast(@dbObjectId as varchar) + \')\'\r\n\r\n        set @select1 = @select1 + \' a" +
                    "nd (1 = 0 \' + @whereCols0 + @whereCols1 + @whereCols2 + @whereCols3 + \')\'\r\n     " +
                    "   set @select1 = \'SELECT count(*) FROM (\' + @select1 + \') count1\'\r\n\r\n        --" +
                    "print @select1\r\n\r\n        begin try\r\n            --print @select1\r\n            I" +
                    "nsert Into #Data1([Count])\r\n            exec(@select1)\r\n        end try\r\n       " +
                    " begin catch\r\n        end catch\r\n\r\n        fetch next from cData1 into @dbObject" +
                    "Id, @dbObjectTypeId, @DbObjectName, @DbObjectSchema\r\n    end\r\n    close cData1\r\n" +
                    "    deallocate cData1\r\n\r\n\tSELECT SUM([Count]) FROM #Data1\r\n\r\n    DROP TABLE #Dat" +
                    "a1\r\n\r\n");
            
            #line 115 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"

}
else
{

            
            #line default
            #line hidden
            this.Write("SELECT  count (*)\r\nFROM [");
            
            #line 121 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 121 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] AS [Project1]\r\n\t");
            
            #line 122 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"

	WriteWhereFilter();
	WriteFilter();
	
            
            #line default
            #line hidden
            
            #line 126 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetGridCount.tt"
}
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
