// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using QueryBuilder.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetItemsForAutocomplete.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetItemsForAutocomplete : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\nSELECT top 10 \r\n\t[Project1].[");
            
            #line 9 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetItemsForAutocomplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] as [Id]\r\n\t,[Project1].[CaptionDisplay] as [Caption]\r\n\t");
            
            #line 11 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetItemsForAutocomplete.tt"
 if (vwProjection.DbObject_Schema == "dbo" && vwProjection.DbObject_Name == "Directory") {
	
            
            #line default
            #line hidden
            this.Write(",(case [Project1].[DirectoryType_FK] when 2 then \'Contact\' when 3 then \'Contracto" +
                    "r\' when 4 then \'DirectoryBranch\' else \'Company\' end) as [MainProjection]\r\n\t");
            
            #line 13 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetItemsForAutocomplete.tt"
 } 
            
            #line default
            #line hidden
            this.Write("FROM [");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetItemsForAutocomplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetItemsForAutocomplete.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] as [Project1]\r\n");
            
            #line 15 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetItemsForAutocomplete.tt"

WriteWhereFilter();
WriteFilter();

            
            #line default
            #line hidden
            this.Write("and [CaptionDisplay] like N\'%\' + @searchText + N\'%\'\r\nFOR JSON PATH\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
