// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using QueryBuilder.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetPage : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n\tSET NOCOUNT ON; \r\n\r\n\tSELECT\r\n\t\t");
            
            #line 11 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(draw));
            
            #line default
            #line hidden
            this.Write(" as [draw]\r\n\t\t,(\r\n\t\t\tSELECT count (*)\r\n\t\t\tFROM [");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] AS [Project1]\r\n\t\t\t\t");
            
            #line 15 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

				PushIndent("				");
				WriteWhereFilter();
				PopIndent();
				
            
            #line default
            #line hidden
            this.Write("\t\t) as [recordsTotal]\r\n\t\t,(\r\n\t\t\tSELECT  count (*)\r\n\t\t\tFROM [");
            
            #line 23 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 23 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] AS [Project1]\r\n\t\t\t\t");
            
            #line 24 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

				PushIndent("				");
				WriteWhereFilter();
				WriteFilter();
				PopIndent();
				
            
            #line default
            #line hidden
            this.Write("\t\t) as [recordsFiltered]\r\n\t\t");
            
            #line 30 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 if (vwProjection.DbObject_Name == "Email") { 
            
            #line default
            #line hidden
            this.Write("\t\t,(\r\n\t\t\tSELECT  count (*)\r\n\t\t\tFROM [");
            
            #line 33 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 33 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] AS [Project1]\r\n\t\t\t\t");
            
            #line 34 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

				PushIndent("				");
				WriteWhereFilter();
				WriteFilter();
            
            #line default
            #line hidden
            this.Write("\t\t\t\tand [Project1].[IsLinkedWithVistos] = 1\r\n\t\t\t\t");
            
            #line 39 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
PopIndent();
				
            
            #line default
            #line hidden
            this.Write("\t\t) as [recordsFilteredEmaiIsLinkedWithVistos]\r\n\t\t");
            
            #line 41 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t,(\r\n\t\tSELECT TOP ");
            
            #line 43 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(length));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t[Entity1].[Id]\r\n\t\t\t");
            
            #line 45 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

			if (vwProjection.DbPrimaryColumn_Name.ToUpper() != "ID")
			{
            
            #line default
            #line hidden
            this.Write("\t\t\t,[Entity1].[");
            
            #line 48 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t\t");
            
            #line 49 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 50 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
if (vwProjection.DbObjectType_Id == 1 || vwProjection.DbObjectType_Id == 5)
			{
            
            #line default
            #line hidden
            this.Write(",[Entity1].[CaptionDisplay] as [Caption] \r\n");
            
            #line 53 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 if (vwProjection.DbObject_Schema == "dbo" && vwProjection.DbObject_Name == "Directory") {

            
            #line default
            #line hidden
            this.Write(",[Entity1].[MainProjection] as [MainProjection] \r\n");
            
            #line 55 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 }
			}
			PushIndent("			");
			foreach(var col in columns.Where(c => columnsVisible.Contains(c.ProjectionColumn_Name))){
				WriteColumnForEntity1Select(col);
				Write(Environment.NewLine);
			}
			PopIndent();
			foreach(var col in columnsVisible.Where(c => c.StartsWith("Role__"))){
            
            #line default
            #line hidden
            this.Write("\t\t\t,[Entity1].[");
            
            #line 64 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col));
            
            #line default
            #line hidden
            this.Write("] as [");
            
            #line 64 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t\t");
            
            #line 65 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

			}
			
            
            #line default
            #line hidden
            this.Write("\t\tFROM (\r\n\t\t\tSELECT\r\n\t\t\t\t[Project1].[");
            
            #line 70 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] as [Id]\r\n\t\t\t\t");
            
            #line 71 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

				if (vwProjection.DbPrimaryColumn_Name.ToUpper() != "ID")
				{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t,[Project1].[");
            
            #line 74 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("] as [");
            
            #line 74 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t\t\t");
            
            #line 75 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 76 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

				if (vwProjection.DbObjectType_Id == 1 || vwProjection.DbObjectType_Id == 5)
				{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t,[Project1].[CaptionSort]\r\n\t\t\t\t,[Project1].[CaptionDisplay]\r\n\t\t\t\t");
            
            #line 81 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 if (vwProjection.DbObject_Schema == "dbo" && vwProjection.DbObject_Name == "Directory") {
				
            
            #line default
            #line hidden
            this.Write(",(case [Project1].[DirectoryType_FK] when 2 then \'Contact\' when 3 then \'Contracto" +
                    "r\' when 4 then \'DirectoryBranch\' else \'Company\' end) as [MainProjection]\r\n\t\t\t\t");
            
            #line 83 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 }
				}
				PushIndent("				");
				foreach(var col in columns.Where(c => columnsVisible.Contains(c.ProjectionColumn_Name) || c.ProjectionColumn_Name == sortOrderColumnName)){
					WriteColumnForProject1Select(col);
					Write(Environment.NewLine);
				}
				PopIndent();
				foreach(var col in columnsVisible.Where(c => c.StartsWith("Role__"))){
            
            #line default
            #line hidden
            this.Write(@"				,(	STUFF((
						SELECT ',' + usr1.[CaptionDisplay]
						FROM [crm].[Participant] part1
						INNER JOIN [crm].[User] usr1 ON usr1.[Deleted] = 0 AND usr1.[Id] = part1.[User_FK]
						INNER JOIN [crm].[DbObjectRole] dor1 ON dor1.[Deleted] = 0 AND dor1.[Id] = part1.[DbObjectRole_FK] AND dor1.[DbObject_FK] = ");
            
            #line 96 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\tINNER JOIN [crm].[Role] role1 ON role1.[Deleted] = 0 AND role1.[Id] = dor" +
                    "1.[Role_FK] AND role1.[Name] = \'");
            
            #line 97 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Replace("Role__","")));
            
            #line default
            #line hidden
            this.Write("\'\r\n\t\t\t\t\t\tWHERE part1.[Deleted] = 0\r\n\t\t\t\t\t\t\tAND part1.[RecordId] = [Project1].[");
            
            #line 99 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbPrimaryColumn_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t\t\t\t\tFOR XML PATH(\'\')\r\n\t\t\t\t\t),1,1,\'\')\r\n\t\t\t\t) as [");
            
            #line 102 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 102 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

				}
				
            
            #line default
            #line hidden
            this.Write("\t\t\t\t,row_number() OVER (ORDER BY ");
            
            #line 105 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortOrder_Project));
            
            #line default
            #line hidden
            this.Write(") AS [row_number]\r\n\t\t\tFROM  [");
            
            #line 106 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 106 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] AS [Project1]\r\n\t\t\t");
            
            #line 107 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
 
				PushIndent("			");
				WriteLeftOuterJoin(WriteLeftOuterJoinType.ForData);
				PopIndent();
			
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 112 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"

				PushIndent("				");
				WriteWhereFilter();
				WriteFilter();
				PopIndent();
				
            
            #line default
            #line hidden
            this.Write("\t\t\t) AS [Entity1]\r\n\t\tWHERE [Entity1].[row_number] > ");
            
            #line 119 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(start));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tORDER BY ");
            
            #line 120 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortOrder_Entity));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tFOR JSON PATH, INCLUDE_NULL_VALUES\r\n\t) as [data]\r\n\tFOR JSON PATH, WITHOUT_ARR" +
                    "AY_WRAPPER");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
