// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using QueryBuilder.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GetPage_EntityActivity : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nSET NOCOUNT ON\r\n\r\n    declare @parentRecordId int = ");
            
            #line 10 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentEntityId));
            
            #line default
            #line hidden
            this.Write("\r\n    declare @parentDbObjectId int = ");
            
            #line 11 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentDbObject_Id));
            
            #line default
            #line hidden
            this.Write("\r\n    declare @filterString nvarchar(max) = N\'");
            
            #line 12 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FilterString));
            
            #line default
            #line hidden
            this.Write("\'\r\n\tdeclare @roledAssignedToId int = (SELECT TOP 1 [Id] FROM [crm].[Role] WHERE [" +
                    "Deleted] = 0 and [Name] = \'AssignedTo\')\r\n\r\n    CREATE TABLE #RoleAssignedToUser(" +
                    "\r\n        [Id] [int]\r\n    )\r\n\r\n\tif (len(isnull(JSON_QUERY(@filterString, \'$.Role" +
                    "__AssignedTo\'), N\'\')) > 2)\r\n\tBEGIN\r\n\t\tInsert Into #RoleAssignedToUser([Id])\r\n\t\tS" +
                    "ELECT JSON_VALUE(value, \'$.UserId\')\r\n\t\tFROM OPENJSON(JSON_QUERY(@filterString, \'" +
                    "$.Role__AssignedTo\'))\r\n\tEND\r\n\r\n    CREATE TABLE #Data1(\r\n        [Id] [int],\r\n  " +
                    "      [DbObjectId] [int],\r\n        [DbObjectName] [varchar](250),\r\n        [DbOb" +
                    "jectSchema] [varchar](50),\r\n        [MainProjection] [varchar](250),\r\n        [N" +
                    "ame] [nvarchar](2000),\r\n        [Created] [datetime],\r\n        [Modified] [datet" +
                    "ime],\r\n        [CreatedBy_FK] [int],\r\n        [ModifiedBy_FK] [int],\r\n    )\r\n\r\n " +
                    "   declare @dbObjectId int\r\n    declare @DbObjectName [varchar](250)\r\n    declar" +
                    "e @DbObjectSchema [varchar](50)\r\n    declare @dbObjectTypeId int\r\n    declare cD" +
                    "ata1 cursor local for\r\n            SELECT distinct\r\n                [Id]\r\n      " +
                    "          ,[DbObjectType_FK]\r\n                ,[Name]\r\n                ,[Schema]" +
                    "\r\n            FROM (\r\n                SELECT distinct\r\n                    vwp1." +
                    "[DbObject_Id] as [Id]\r\n                    ,vwp1.[DbObjectType_Id] as [DbObjectT" +
                    "ype_FK]\r\n                    ,vwp1.[DbObject_Name] as [Name]\r\n                  " +
                    "  ,vwp1.[DbObject_Schema] as [Schema]\r\n                FROM [crm].[DbColumn] c1\r" +
                    "\n                INNER JOIN [crm].[vwProjection] vwp1 on vwp1.[DbObject_Id] = c1" +
                    ".[DbObject_FK] and vwp1.[Projection_ActivityEnabled] = 1 and vwp1.[Profile_Id] =" +
                    " @profileId and vwp1.[AccessRight] > 0\r\n                WHERE c1.[Deleted] = 0\r\n" +
                    "                    and c1.[ReferenceDbObject_FK] = @parentDbObjectId\r\n         " +
                    "           and vwp1.[DbObjectType_Id] in (1, 5)\r\n                UNION\r\n        " +
                    "        SELECT distinct\r\n                    vwp1.[DbObject_Id] as [Id]\r\n       " +
                    "             ,vwp1.[DbObjectType_Id] as [DbObjectType_FK]\r\n                    ," +
                    "vwp1.[DbObject_Name] as [Name]\r\n                    ,vwp1.[DbObject_Schema] as [" +
                    "Schema]\r\n                FROM [crm].[DbObjectDbObject] oo1\r\n                INNE" +
                    "R JOIN [crm].[vwProjection] vwp1 on vwp1.[DbObject_Id] = oo1.[RightDbObject_FK] " +
                    "and vwp1.[Projection_ActivityEnabled] = 1 and vwp1.[Profile_Id] = @profileId and" +
                    " vwp1.[AccessRight] > 0\r\n                where oo1.[Deleted] = 0 and oo1.[LeftDb" +
                    "Object_FK] = @parentDbObjectId and oo1.[LeftRecordId] = @parentDbObjectId\r\n     " +
                    "           UNION\r\n                SELECT distinct\r\n                    vwp1.[DbO" +
                    "bject_Id] as [Id]\r\n                    ,vwp1.[DbObjectType_Id] as [DbObjectType_" +
                    "FK]\r\n                    ,vwp1.[DbObject_Name] as [Name]\r\n                    ,v" +
                    "wp1.[DbObject_Schema] as [Schema]\r\n                FROM [crm].[DbObjectDbObject]" +
                    " oo1\r\n                INNER JOIN [crm].[vwProjection] vwp1 on vwp1.[DbObject_Id]" +
                    " = oo1.[LeftDbObject_FK] and vwp1.[Projection_ActivityEnabled] = 1 and vwp1.[Pro" +
                    "file_Id] = @profileId and vwp1.[AccessRight] > 0\r\n                where oo1.[Del" +
                    "eted] = 0 and oo1.[RightDbObject_FK] = @parentDbObjectId and oo1.[RightRecordId]" +
                    " = @parentDbObjectId\r\n            ) obj1\r\n\r\n    open cData1\r\n    fetch next from" +
                    " cData1 into @dbObjectId, @dbObjectTypeId, @DbObjectName, @DbObjectSchema\r\n    w" +
                    "hile @@FETCH_STATUS=0\r\n    begin\r\n        declare @whereCols0 varchar(max) = \'\'\r" +
                    "\n        declare @whereCols1 varchar(max) = \'\'\r\n        declare @whereCols2 varc" +
                    "har(max) = \'\'\r\n        declare @whereCols3 varchar(max) = \'\'\r\n        declare @s" +
                    "elect1 varchar(max) = \'\'\r\n\r\n        set @select1 = \'SELECT distinct \' + CAST(@db" +
                    "ObjectId as varchar) + \' as [DbObjectId],\'\'\' + @DbObjectName + \'\'\' as [DbObjectN" +
                    "ame],\'\'\' + @DbObjectSchema + \'\'\' as [DbObjectSchema], Entity1.[Id] as [RecordId]" +
                    ",\' + IIF(@DbObjectName=\'Directory\',\'(case Entity1.[DirectoryType_FK] when 2 then" +
                    " \'\'Contact\'\' when 3 then \'\'Contractor\'\' when 4 then \'\'DirectoryBranch\'\' else \'\'C" +
                    "ompany\'\' end)\',\'\'\'\' + @DbObjectName + \'\'\'\') + \' as [MainProjection], Entity1.[Ca" +
                    "ptionDisplay] as [Caption], Entity1.[Created], Entity1.[Modified], Entity1.[Crea" +
                    "tedBy_FK], Entity1.[ModifiedBy_FK]\'\r\n        set @select1 = @select1 + \' FROM [\'" +
                    " + @DbObjectSchema + \'].[\' + @DbObjectName + \'] as Entity1 \'\r\n\r\n        IF (@dbO" +
                    "bjectTypeId = 1)\r\n        BEGIN\r\n            set @select1 = @select1 + \' WHERE E" +
                    "ntity1.[Deleted] = 0 \'\r\n        END\r\n        ELSE\r\n        BEGIN\r\n            se" +
                    "t @select1 = @select1 + \' WHERE 1 = 1 \'\r\n        END\r\n\r\n        SELECT @whereCol" +
                    "s1 = coalesce(@whereCols1 + \'\', \'\') + \'or Entity1.[\' + convert(varchar,c1.[Name]" +
                    ") + \'] = \' + CAST(@parentRecordId as varchar) + \' \'\r\n        FROM [crm].[DbColum" +
                    "n] c1\r\n        WHERE c1.[Deleted] = 0\r\n            and c1.DbObject_FK = @dbObjec" +
                    "tId\r\n            and c1.[ReferenceDbObject_FK] = @parentDbObjectId\r\n            " +
                    "and c1.[ComputedExpression] is null\r\n        order by c1.QueueOrder\r\n\r\n        s" +
                    "et @whereCols2 = \' or Entity1.[Id] in (SELECT oo1.[LeftRecordId] FROM [crm].[DbO" +
                    "bjectDbObject] oo1 WHERE oo1.[Deleted] = 0 and oo1.[RightDbObject_FK] = \' + cast" +
                    "(@parentDbObjectId as varchar) + \' and oo1.[RightRecordId] = \' + cast(@parentRec" +
                    "ordId as varchar) + \' and oo1.[LeftDbObject_FK] = \' + cast(@dbObjectId as varcha" +
                    "r) + \')\'\r\n        set @whereCols3 = \' or Entity1.[Id] in (SELECT oo1.[RightRecor" +
                    "dId] FROM [crm].[DbObjectDbObject] oo1 WHERE oo1.[Deleted] = 0 and oo1.[LeftDbOb" +
                    "ject_FK] = \' + cast(@parentDbObjectId as varchar) + \' and oo1.[LeftRecordId] = \'" +
                    " + cast(@parentRecordId as varchar) + \' and oo1.[RightDbObject_FK] = \' + cast(@d" +
                    "bObjectId as varchar) + \')\'\r\n\r\n        set @select1 = @select1 + \' and (1 = 0 \' " +
                    "+ @whereCols0 + @whereCols1 + @whereCols2 + @whereCols3 + \')\'\r\n\r\n        --print" +
                    " @select1\r\n\r\n        begin try\r\n            --print @select1\r\n            Insert" +
                    " Into #Data1([DbObjectId], [DbObjectName], [DbObjectSchema], [Id], [MainProjecti" +
                    "on], [Name], [Created], [Modified], [CreatedBy_FK], [ModifiedBy_FK])\r\n          " +
                    "  exec(@select1)\r\n        end try\r\n        begin catch\r\n        end catch\r\n\r\n   " +
                    "     fetch next from cData1 into @dbObjectId, @dbObjectTypeId, @DbObjectName, @D" +
                    "bObjectSchema\r\n    end\r\n    close cData1\r\n    deallocate cData1\r\n\r\n    SELECT\r\n " +
                    "       ");
            
            #line 131 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(draw));
            
            #line default
            #line hidden
            this.Write(" as [draw]\r\n        ,(\r\n            SELECT count (*)\r\n            FROM #Data1 AS " +
                    "[Project1]\r\n        ) as [recordsTotal]\r\n        ,(\r\n            SELECT count (*" +
                    ")\r\n            FROM #Data1 AS [Project1]\r\n\t\t\tWHERE [Project1].[Id] > 0\r\n\t\t\t\tand " +
                    "((len(isnull(JSON_VALUE(@filterString, \'$.Created_From\'), N\'\')) > 0 and ([Projec" +
                    "t1].[Created] >= cast((JSON_VALUE(@filterString, \'$.Created_From\')) as datetime)" +
                    ")) or (len(isnull(JSON_VALUE(@filterString, \'$.Created_From\'), N\'\')) = 0))\r\n\t\t\t\t" +
                    "and ((len(isnull(JSON_VALUE(@filterString, \'$.Created_To\'), N\'\')) > 0 and ([Proj" +
                    "ect1].[Created] < cast((JSON_VALUE(@filterString, \'$.Created_To\')) as datetime))" +
                    ") or (len(isnull(JSON_VALUE(@filterString, \'$.Created_To\'), N\'\')) = 0))\r\n\t\t\t\tand" +
                    " ((len(isnull(JSON_VALUE(@filterString, \'$.Modified_From\'), N\'\')) > 0 and ([Proj" +
                    "ect1].[Modified] >= cast((JSON_VALUE(@filterString, \'$.Modified_From\')) as datet" +
                    "ime))) or (len(isnull(JSON_VALUE(@filterString, \'$.Modified_From\'), N\'\')) = 0))\r" +
                    "\n\t\t\t\tand ((len(isnull(JSON_VALUE(@filterString, \'$.Modified_To\'), N\'\')) > 0 and " +
                    "([Project1].[Modified] < cast((JSON_VALUE(@filterString, \'$.Modified_To\')) as da" +
                    "tetime))) or (len(isnull(JSON_VALUE(@filterString, \'$.Modified_To\'), N\'\')) = 0))" +
                    "\r\n\t\t\t\tand ((len(isnull(JSON_QUERY(@filterString, \'$.ProjectionLoc\'), N\'\')) > 2 a" +
                    "nd\r\n\t\t\t\t\t\t(\r\n\t\t\t\t\t\t\t[Project1].[MainProjection] COLLATE SQL_Latin1_General_CP1_C" +
                    "I_AS in (SELECT p11.[Name] FROM [crm].[Projection] p11 WHERE p11.[Deleted] = 0 a" +
                    "nd p11.[ActivityEnabled] = 1 and p11.[Id] in (SELECT value FROM STRING_SPLIT(rep" +
                    "lace(replace(JSON_QUERY(@filterString, \'$.ProjectionLoc\'), \'[\',\'\'), \']\', \'\'), \'," +
                    "\')  where len(isnull(value, \'\')) > 0))\r\n\t\t\t\t\t\t)\r\n\t\t\t\t\t) or (len(isnull(JSON_QUER" +
                    "Y(@filterString, \'$.ProjectionLoc\'), N\'\')) <= 2))\r\n\t\t\t\tand (((SELECT count(*) FR" +
                    "OM #RoleAssignedToUser) > 0 and \r\n\t\t\t\t\t\t(\r\n\t\t\t\t\t\t\t[Project1].[Id] in (\r\n\t\t\t\t\t   " +
                    "                         SELECT part1.[RecordId]\r\n\t\t\t\t\t                         " +
                    "   FROM [crm].[Role] role1\r\n\t\t\t\t\t                            INNER JOIN [crm].[D" +
                    "bObjectRole] orole1 on orole1.[Deleted] = 0 and orole1.[DbObject_FK] = [Project1" +
                    "].[DbObjectId] and orole1.[Role_FK] = role1.[Id]\r\n\t\t\t\t\t                         " +
                    "   INNER JOIN [crm].[Participant] part1 on part1.[Deleted] = 0 and part1.[DbObje" +
                    "ctRole_FK] = orole1.[Id] and part1.[User_FK] in (SELECT [Id] FROM #RoleAssignedT" +
                    "oUser)\r\n\t\t\t\t\t                            WHERE role1.[Deleted] = 0 and role1.[Id" +
                    "] = @roledAssignedToId\r\n\t\t\t\t                            )\r\n\t\t\t\t\t\t)\r\n\t\t\t\t\t) or ((" +
                    "SELECT count(*) FROM #RoleAssignedToUser) = 0))        ) as [recordsFiltered]\r\n " +
                    "       ,(\r\n        SELECT TOP ");
            
            #line 161 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(length));
            
            #line default
            #line hidden
            this.Write("\r\n            [Entity1].[Id]\r\n            ,[Entity1].[Name]\r\n            ,[Entity" +
                    "1].[Name] as [Caption]\r\n            ,[Entity1].[Created]\r\n            ,[Entity1]" +
                    ".[Modified]\r\n            ,(SELECT TOP 1 p1.[CaptionDisplay] FROM [crm].[User] p1" +
                    " WHERE p1.[Deleted] = 0 and p1.[Id] = [Entity1].[CreatedBy_FK]) as [CreatedBy_FK" +
                    "]\r\n            ,(SELECT TOP 1 p1.[CaptionDisplay] FROM [crm].[User] p1 WHERE p1." +
                    "[Deleted] = 0 and p1.[Id] = [Entity1].[ModifiedBy_FK]) as [ModifiedBy_FK]\r\n     " +
                    "       ,[Entity1].[MainProjection]\r\n            ,(SELECT TOP 1 p1.[Icon] FROM [c" +
                    "rm].[Projection] p1 WHERE p1.[Deleted] = 0 and p1.[Name] COLLATE SQL_Latin1_Gene" +
                    "ral_CP1_CI_AS = [Entity1].[MainProjection]) as [Icon]\r\n            ,isnull((SELE" +
                    "CT TOP 1 ls.[value] FROM [crm].[LocalizationString] ls WHERE ls.[Language_Fk] = " +
                    "@userLanguageId and ls.[Area_Fk] = (SELECT TOP 1 la1.[Id] FROM [crm].[Localizati" +
                    "onArea] la1 WHERE la1.[Name] COLLATE SQL_Latin1_General_CP1_CI_AS = [Entity1].[M" +
                    "ainProjection]) and ls.[key] = \'NameTitle\' ORDER BY [customized] DESC) , [Entity" +
                    "1].[MainProjection]) as [ProjectionLoc]\r\n            ,(    STUFF((\r\n            " +
                    "            SELECT \',\' + usr1.[CaptionDisplay]\r\n                        FROM [cr" +
                    "m].[Participant] part1\r\n                        INNER JOIN [crm].[User] usr1 ON " +
                    "usr1.[Deleted] = 0 AND usr1.[Id] = part1.[User_FK]\r\n                        INNE" +
                    "R JOIN [crm].[DbObjectRole] dor1 ON dor1.[Deleted] = 0 AND dor1.[Id] = part1.[Db" +
                    "ObjectRole_FK] AND dor1.[DbObject_FK] = [Entity1].[DbObjectId]\r\n                " +
                    "        INNER JOIN [crm].[Role] role1 ON role1.[Deleted] = 0 AND role1.[Id] = do" +
                    "r1.[Role_FK] AND role1.[Name] = \'AssignedTo\'\r\n                        WHERE part" +
                    "1.[Deleted] = 0\r\n                            AND part1.[RecordId] = [Entity1].[I" +
                    "d]\r\n                        FOR XML PATH(\'\')\r\n                    ),1,1,\'\')\r\n   " +
                    "             ) as [Role__AssignedTo]\r\n        FROM (\r\n            SELECT\r\n      " +
                    "          [Project1].[Id] as [Id]\r\n                ,[Project1].[Name] as [Name]\r" +
                    "\n                ,[Project1].[Created] as [Created]\r\n                ,[Project1]" +
                    ".[Modified] as [Modified]\r\n                ,[Project1].[CreatedBy_FK] as [Create" +
                    "dBy_FK]\r\n                ,[Project1].[ModifiedBy_FK] as [ModifiedBy_FK]\r\n       " +
                    "         ,[Project1].[MainProjection] as [MainProjection]\r\n                ,[Pro" +
                    "ject1].[DbObjectId] as [DbObjectId]\r\n                ,row_number() OVER (ORDER B" +
                    "Y ");
            
            #line 193 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortOrder_Project));
            
            #line default
            #line hidden
            this.Write(") AS [row_number]\r\n            FROM  #Data1 AS [Project1]\r\n\t\t\tWHERE [Project1].[I" +
                    "d] > 0\r\n\t\t\t\tand ((len(isnull(JSON_VALUE(@filterString, \'$.Created_From\'), N\'\')) " +
                    "> 0 and ([Project1].[Created] >= cast((JSON_VALUE(@filterString, \'$.Created_From" +
                    "\')) as datetime))) or (len(isnull(JSON_VALUE(@filterString, \'$.Created_From\'), N" +
                    "\'\')) = 0))\r\n\t\t\t\tand ((len(isnull(JSON_VALUE(@filterString, \'$.Created_To\'), N\'\')" +
                    ") > 0 and ([Project1].[Created] < cast((JSON_VALUE(@filterString, \'$.Created_To\'" +
                    ")) as datetime))) or (len(isnull(JSON_VALUE(@filterString, \'$.Created_To\'), N\'\')" +
                    ") = 0))\r\n\t\t\t\tand ((len(isnull(JSON_VALUE(@filterString, \'$.Modified_From\'), N\'\')" +
                    ") > 0 and ([Project1].[Modified] >= cast((JSON_VALUE(@filterString, \'$.Modified_" +
                    "From\')) as datetime))) or (len(isnull(JSON_VALUE(@filterString, \'$.Modified_From" +
                    "\'), N\'\')) = 0))\r\n\t\t\t\tand ((len(isnull(JSON_VALUE(@filterString, \'$.Modified_To\')" +
                    ", N\'\')) > 0 and ([Project1].[Modified] < cast((JSON_VALUE(@filterString, \'$.Modi" +
                    "fied_To\')) as datetime))) or (len(isnull(JSON_VALUE(@filterString, \'$.Modified_T" +
                    "o\'), N\'\')) = 0))\r\n\t\t\t\tand ((len(isnull(JSON_QUERY(@filterString, \'$.ProjectionLo" +
                    "c\'), N\'\')) > 2 and\r\n\t\t\t\t\t\t(\r\n\t\t\t\t\t\t\t[Project1].[MainProjection] COLLATE SQL_Lati" +
                    "n1_General_CP1_CI_AS in (SELECT p11.[Name] FROM [crm].[Projection] p11 WHERE p11" +
                    ".[Deleted] = 0 and p11.[ActivityEnabled] = 1 and p11.[Id] in (SELECT value FROM " +
                    "STRING_SPLIT(replace(replace(JSON_QUERY(@filterString, \'$.ProjectionLoc\'), \'[\',\'" +
                    "\'), \']\', \'\'), \',\')  where len(isnull(value, \'\')) > 0))\r\n\t\t\t\t\t\t)\r\n\t\t\t\t\t) or (len(" +
                    "isnull(JSON_QUERY(@filterString, \'$.ProjectionLoc\'), N\'\')) <= 2))\r\n\t\t\t\tand (((SE" +
                    "LECT count(*) FROM #RoleAssignedToUser) > 0 and \r\n\t\t\t\t\t\t(\r\n\t\t\t\t\t\t\t[Project1].[Id" +
                    "] in (\r\n\t\t\t\t\t                            SELECT part1.[RecordId]\r\n\t\t\t\t\t         " +
                    "                   FROM [crm].[Role] role1\r\n\t\t\t\t\t                            INN" +
                    "ER JOIN [crm].[DbObjectRole] orole1 on orole1.[Deleted] = 0 and orole1.[DbObject" +
                    "_FK] = [Project1].[DbObjectId] and orole1.[Role_FK] = role1.[Id]\r\n\t\t\t\t\t         " +
                    "                   INNER JOIN [crm].[Participant] part1 on part1.[Deleted] = 0 a" +
                    "nd part1.[DbObjectRole_FK] = orole1.[Id] and part1.[User_FK] in (SELECT [Id] FRO" +
                    "M #RoleAssignedToUser)\r\n\t\t\t\t\t                            WHERE role1.[Deleted] =" +
                    " 0 and role1.[Id] = @roledAssignedToId\r\n\t\t\t\t                            )\r\n\t\t\t\t\t" +
                    "\t)\r\n\t\t\t\t\t) or ((SELECT count(*) FROM #RoleAssignedToUser) = 0))            ) AS " +
                    "[Entity1]\r\n\t\tWHERE [Entity1].[row_number] > ");
            
            #line 216 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(start));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tORDER BY ");
            
            #line 217 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\GetPage_EntityActivity.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortOrder_Entity));
            
            #line default
            #line hidden
            this.Write("\r\n        FOR JSON PATH, INCLUDE_NULL_VALUES\r\n    ) as [data]\r\n    FOR JSON PATH," +
                    " WITHOUT_ARRAY_WRAPPER\r\n\r\n    DROP TABLE #Data1\r\n\tDROP TABLE #RoleAssignedToUser" +
                    "\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
