// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Import : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n");
            this.Write(@"
DECLARE @defaultCurrencyCode as varchar(10) = (Select top 1 ss.[DefaultCurrency_FK] from crm.[SystemSettings] ss where ss.[Deleted] = 0 Order By ss.[Id])
DECLARE @defaultCurrencyId as int = (Select top 1 c.[Id] from [crm].[Currency] c where c.[IsoCode] = @defaultCurrencyCode AND c.[Deleted] = 0)
--DECLARE @IssuerAccount_FK int = [crm].[GetDefaultCompanyID]()

BEGIN TRY 
	BEGIN TRANSACTION

	--update
	UPDATE [");
            
            #line 15 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 15 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\tSET \r\n\t\t  [Deleted] = json.Deleted\r\n\t\t,[ModifiedBy_FK] = @userId\r\n\t\t,[Modifi" +
                    "ed] = getdate()\r\n");
            
            #line 20 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
 
			PushIndent("		");

			foreach(var col in columns){
				WriteUpdateColumn(col);
			}
			PopIndent();

            
            #line default
            #line hidden
            this.Write("\tFROM OPENJSON(@json)\r\n\t\tWITH (\t\r\n\t\t\t[Deleted] [bit]\r\n");
            
            #line 31 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
 
			PushIndent("			");
			foreach(var col in columns){
				WriteJsonColumn(col);
			}
			PopIndent();

            
            #line default
            #line hidden
            this.Write("\t) AS json\r\n\tWHERE [");
            
            #line 39 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 39 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 39 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pairingColumn));
            
            #line default
            #line hidden
            this.Write("] = json.[");
            
            #line 39 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pairingColumn));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\tAND json.[Deleted] = 0\r\n\t--update\r\n\r\n\t--delete\r\n\tUPDATE [");
            
            #line 44 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 44 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\tSET \r\n\t\t  [Deleted] = json.Deleted\r\n\t\t,[ModifiedBy_FK] = @userId\r\n\t\t,[Modifi" +
                    "ed] = getdate()\r\n\tFROM OPENJSON(@json)\r\n\t\tWITH (\t\r\n\t\t\t[Deleted] [bit]\r\n");
            
            #line 52 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
 
			PushIndent("			");
			WriteJsonColumn(columns.Where(x => x.ProjectionColumn_Name == pairingColumn).First());
			PopIndent();

            
            #line default
            #line hidden
            this.Write("\t) AS json\r\n\tWHERE [");
            
            #line 58 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 58 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 58 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pairingColumn));
            
            #line default
            #line hidden
            this.Write("] = json.[");
            
            #line 58 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pairingColumn));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\tAND json.[Deleted] = 1\r\n\t--delete\r\n\r\n\t--insert\r\n\tINSERT INTO [");
            
            #line 63 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 63 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t([Deleted]\r\n\t\t,[CreatedBy_FK]\r\n\t\t,[Created]\r\n\t\t,[ModifiedBy_FK]\r\n\t\t,[Modifie" +
                    "d]\r\n");
            
            #line 69 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
 
		PushIndent("		");
		foreach(var col in columns){
			WriteInsertColumn(col);
		}
		foreach(var col in newActionColumns){
			WriteInsertColumn(col);
		}
		PopIndent();

            
            #line default
            #line hidden
            this.Write("\t\t)\r\n\tSELECT\r\n\t\t0\r\n\t\t,@userId\r\n\t\t,getdate()\r\n\t\t,NULL\r\n\t\t,getdate()\r\n");
            
            #line 85 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
 
		PushIndent("		");
		foreach(var col in columns){
			WriteSelectColumn(col);
		}
		foreach(var col in newActionColumns){
			WriteSelectColumn(col);
		}
		PopIndent();

            
            #line default
            #line hidden
            this.Write("\tFROM OPENJSON(@json)\r\n\tWITH (\r\n\t\t[Deleted] [bit]\r\n");
            
            #line 97 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
 
		PushIndent("		");
		foreach(var col in columns){
			WriteJsonColumn(col);
		}
		PopIndent();

            
            #line default
            #line hidden
            this.Write("\t) AS json\r\n\tWHERE json.[");
            
            #line 104 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pairingColumn));
            
            #line default
            #line hidden
            this.Write("] NOT IN (SELECT old.[");
            
            #line 104 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pairingColumn));
            
            #line default
            #line hidden
            this.Write("] FROM [");
            
            #line 104 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 104 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("] old WHERE old.[Deleted] = 0 AND old.[");
            
            #line 104 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Import.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pairingColumn));
            
            #line default
            #line hidden
            this.Write(@"] IS NOT NULL)
		AND json.[Deleted] = 0
	--insert

	COMMIT TRANSACTION
END TRY
BEGIN CATCH 
	IF (@@TRANCOUNT > 0)
		BEGIN
			ROLLBACK TRANSACTION
		END 
			
		--SELECT
		--	ERROR_NUMBER() AS ErrorNumber,
		--	ERROR_SEVERITY() AS ErrorSeverity,
		--	ERROR_STATE() AS ErrorState,
		--	ERROR_PROCEDURE() AS ErrorProcedure,
		--	ERROR_LINE() AS ErrorLine,
		--	ERROR_MESSAGE() AS ErrorMessage

			declare @ERROR_NUMBER int = 50000;
			declare @ERROR_MESSAGE nvarchar(2048) = (isnull(cast((ERROR_PROCEDURE()) as varchar) + '. ', '') + ERROR_MESSAGE());
			declare @ERROR_STATE int = ERROR_STATE();

			THROW @ERROR_NUMBER, @ERROR_MESSAGE, @ERROR_STATE;
END CATCH


");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
