// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\New.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class New : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
DECLARE @defaultCurrencyCode as varchar(10) = (Select top 1 ss.[DefaultCurrency_FK] from crm.[SystemSettings] ss where ss.[Deleted] = 0 Order By ss.[Id])
DECLARE @defaultCurrencyId as int = (Select top 1 c.[Id] from [crm].[Currency] c where c.[IsoCode] = @defaultCurrencyCode AND c.[Deleted] = 0)
--DECLARE @IssuerAccount_FK int = [crm].[GetDefaultCompanyID]()
 
	
SELECT 
	0 as [Version]
");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\New.tt"
  WriteSelectColumn(); 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 16 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\New.tt"

	if (vwProjection.Object_ParticipantEnabled)
	{
	
            
            #line default
            #line hidden
            this.Write(@"	,(SELECT r1.[Id] as [RoleId]
		,@userId as [UserId]
		,(SELECT TOP 1 u1.[CaptionDisplay] FROM [crm].[User] u1 WHERE u1.[Deleted] = 0 and u1.[Id] = @userId) as [UserCaption]
	  FROM [crm].[Role] r1
	  INNER JOIN [crm].[DbObjectRole] dor1 ON dor1.[Deleted] = 0 AND dor1.[DbObject_FK] = ");
            
            #line 24 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\New.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write(" AND dor1.[Role_FK] = r1.[Id]\r\n\t  WHERE r1.[Deleted] = 0 and r1.[Name] in (\'Assig" +
                    "nedTo\', \'DiscussionParticipant\')\r\n\t  FOR JSON PATH, INCLUDE_NULL_VALUES)\r\n\tas [P" +
                    "articipants]\r\n\t");
            
            #line 28 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\New.tt"

	} 
            
            #line default
            #line hidden
            this.Write("\r\n\tFOR JSON PATH, WITHOUT_ARRAY_WRAPPER \r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
