// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.QueryBuilder.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Update : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("DECLARE @jsonRows NVARCHAR(MAX);\r\n \r\n\tBEGIN TRY\r\n\t\tBEGIN TRANSACTION\r\n\t\t\tUPDATE [" +
                    "");
            
            #line 10 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 10 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\t\tSET \r\n\t\t\t  [ModifiedBy_FK] = @userId\r\n\t\t\t,[Modified] = getdate()\r\n");
            
            #line 14 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
 
			PushIndent("			");
			foreach(var col in columns){
				WriteUpdateColumn(col);
			}
			PopIndent();

            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tFROM OPENJSON(@json)\r\n\t\t\t\tWITH (\r\n");
            
            #line 24 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"

			PushIndent("			");
			bool first = true;
			foreach(var col in columns){
				WriteJsonColumn(col, first);
				first = false;
			}
			PopIndent();

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\r\n\t\t\t\t) AS json\r\n\t\t\t");
            
            #line 34 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
				
				WriteUpdateFilter();
				WriteGrids(); 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\r\n\t\t\t");
            
            #line 38 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
 	if (vwProjection.Object_ParticipantEnabled)
			{
            
            #line default
            #line hidden
            this.Write("\t\t\tDECLARE @jsonParticipants NVARCHAR(MAX) = JSON_QUERY(@json, \'$.Participants\')\r" +
                    "\n\t\t\tIF (ISJSON(@jsonParticipants) > 0)  \r\n\t\t\t\texec sp_api3_UpdateDbObjectPartici" +
                    "pants @jsonParticipants, ");
            
            #line 42 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write(", @userId, @id\r\n\t\t\t");
            
            #line 43 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 45 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
if (vwProjection.Object_DocumentEnabled)
			{
            
            #line default
            #line hidden
            this.Write("\t\t\tDECLARE @jsonDocument NVARCHAR(MAX) = JSON_QUERY(@json, \'$.Document\')\r\n\t\t\tIF (" +
                    "ISJSON(@jsonDocument) > 0)  \r\n\t\t\t\texec sp_api3_UpdateDocuments @jsonDocument,");
            
            #line 49 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Id));
            
            #line default
            #line hidden
            this.Write(",@userId,@id\r\n\t\t\t");
            
            #line 50 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 52 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
if (vwProjection.DbObject_Name == "Email")
			{
            
            #line default
            #line hidden
            this.Write("\t\t\tDECLARE @jsonEmailAttachment NVARCHAR(MAX) = JSON_QUERY(@json, \'$.EmailAttachm" +
                    "ent\')\r\n\t\t\tIF (ISJSON(@jsonEmailAttachment) > 0)  \r\n\t\t\t\texec sp_api3_updateEmailA" +
                    "ttachments @jsonEmailAttachment,@userId,@id\r\n\t\t\t");
            
            #line 57 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t");
            
            #line 59 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
if (vwProjection.Object_CategoriesEnabled)
			{
            
            #line default
            #line hidden
            this.Write("\t\t\tDECLARE @jsonCategory NVARCHAR(MAX) = JSON_QUERY(@json, \'$.Category\')\r\n\t\t\tIF (" +
                    "ISJSON(@jsonCategory) > 0)  \r\n\t\t\t\texec sp_api3_assignCategories \'");
            
            #line 63 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vwProjection.DbObject_Name));
            
            #line default
            #line hidden
            this.Write("\',@id,@jsonCategory\r\n\t\t\t");
            
            #line 64 "P:\WorkEswGitHub\VistosV3.Server.3.2a\VistosV3.Server\Core\QueryBuilder\Templates\Update.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH 
		IF (@@TRANCOUNT > 0)
		   BEGIN
			  ROLLBACK TRANSACTION
		   END 
			
			--SELECT
			--	ERROR_NUMBER() AS ErrorNumber,
			--	ERROR_SEVERITY() AS ErrorSeverity,
			--	ERROR_STATE() AS ErrorState,
			--	ERROR_PROCEDURE() AS ErrorProcedure,
			--	ERROR_LINE() AS ErrorLine,
			--	ERROR_MESSAGE() AS ErrorMessage

				declare @ERROR_NUMBER int = 50000;
				declare @ERROR_MESSAGE nvarchar(2048) = (isnull(cast((ERROR_PROCEDURE()) as varchar) + '. ', '') + ERROR_MESSAGE());
				declare @ERROR_STATE int = ERROR_STATE();

				THROW @ERROR_NUMBER, @ERROR_MESSAGE, @ERROR_STATE;
	END CATCH
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
